### ISSUE TITLE
Create a Post

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-rest-spacemonkey-mafia#39]
As an author, I would like to be able to create Posts so I can share my thoughts with the world.

**Given** a user is in the app  
**When** they select the `New Post` menu option
**Then** they should be directed to a page with a form for creating a new post

**Given** the user has entered the relevant information for a Post
**When** they click the `Save` button  
**Then** the Post should be saved to the database  
**And** the creation datetime should be automatically set to the current date and time  
**And** the post should automatically be approved  
**And** the user should be recorded as the author of the Post  
**And** the user should be redirected to the new Post's details page

The "relevant information" for a Post is

* Title
* Content
* Category
* Publication date (current date)
* Header Image URL (optional)

**Comment by codinglumos** [comment]
2

**Comment by JayMy45** [comment]
Will implement on Client side whenever authentication pull request is merged.  Also need to update author on code as it is commented out at the moment.


```
# Create a Post
    def create(self, request):
        """Handle POST operations

        Returns
            Response -- JSON serialized post instance
        """
        #~ these will need to be updated once the Authentication is Running.
        # author = Author.objects.get(user=request.auth.user)
        category = Category.objects.get(pk=request.data["category"])

        post = Post.objects.create(
            author=request.data["author"],
            category=category,
            title=request.data["title"],
            publication_date=request.data["publication_date"],
            image_url=request.data["image_url"],
            content=request.data["content"],
            approved=request.data["approved"],
        )
        serializer = PostSerializer(post)
        return Response(serializer.data)
```
